#!/usr/bin/env bash
# Usage: ./runsnake 30

# Get directory where the script is located
SOURCE="${BASH_SOURCE[0]}"

while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done

SOURCE_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# Load miniconda
module unload miniconda/4.12.0
module load miniconda/4.12.0 ## should be 4.12.0 or load htslib/1.16 to maintain long file block size

# Init
mkdir -p log

# Get jobs
JOB_COUNT=$1

shift

# Run
snakemake --jobname "{rulename}.{jobid}" --drmaa " -V -cwd -j y -o ./log -e ./log -l h_rt={resources.hrs}:00:00 -l mfree={resources.mem}G -pe serial {threads} -w n -S /bin/bash"\
  -s ${SOURCE_DIR}/Snakefile -j ${JOB_COUNT} \
  --printshellcmds --keep-going --rerun-incomplete --latency-wait 30 \
  --use-singularity --singularity-args "--bind /net:/net" \
  "$@"
